default:    &default
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  pool:     5
  username: root
  password:

development:
  <<: *default
  database: chat_rails5_react_dev

test:
  <<: *default
  database: chat_rails5_react_test

staging:
  <<: *default
  database: chat_rails5_react_staging

production:
  <<: *default
  database: chat_rails5_react_production
